// Mocks generated by Mockito 5.2.0 from annotations
// in vido/test/features/photos_translator/data/repository/photos_translator_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;
import 'dart:convert' as _i9;
import 'dart:io' as _i4;
import 'dart:typed_data' as _i10;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vido/features/photos_translator/data/data_sources/photos_translator_local_data_source.dart'
    as _i8;
import 'package:vido/features/photos_translator/data/data_sources/photos_translator_remote_data_source.dart'
    as _i6;
import 'package:vido/features/photos_translator/domain/entities/pdf_file.dart'
    as _i3;
import 'package:vido/features/photos_translator/domain/entities/translation.dart'
    as _i5;
import 'package:vido/features/photos_translator/domain/entities/translations_file.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeTranslationsFile_0 extends _i1.Fake implements _i2.TranslationsFile {
}

class _FakePdfFile_1 extends _i1.Fake implements _i3.PdfFile {}

class _FakeFile_2 extends _i1.Fake implements _i4.File {}

class _FakeTranslation_3 extends _i1.Fake implements _i5.Translation {}

class _FakeUri_4 extends _i1.Fake implements Uri {}

class _FakeDirectory_5 extends _i1.Fake implements _i4.Directory {}

class _FakeDateTime_6 extends _i1.Fake implements DateTime {}

class _FakeRandomAccessFile_7 extends _i1.Fake implements _i4.RandomAccessFile {
}

class _FakeIOSink_8 extends _i1.Fake implements _i4.IOSink {}

class _FakeFileStat_9 extends _i1.Fake implements _i4.FileStat {}

class _FakeFileSystemEntity_10 extends _i1.Fake
    implements _i4.FileSystemEntity {}

/// A class which mocks [PhotosTranslatorRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhotosTranslatorRemoteDataSource extends _i1.Mock
    implements _i6.PhotosTranslatorRemoteDataSource {
  MockPhotosTranslatorRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.TranslationsFile> createTranslationsFile(String? name) =>
      (super.noSuchMethod(Invocation.method(#createTranslationsFile, [name]),
              returnValue:
                  Future<_i2.TranslationsFile>.value(_FakeTranslationsFile_0()))
          as _i7.Future<_i2.TranslationsFile>);
  @override
  _i7.Future<int> addTranslation(int? fileId, _i5.Translation? translation) =>
      (super.noSuchMethod(
          Invocation.method(#addTranslation, [fileId, translation]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<List<_i3.PdfFile>> getCompletedPdfFiles() =>
      (super.noSuchMethod(Invocation.method(#getCompletedPdfFiles, []),
              returnValue: Future<List<_i3.PdfFile>>.value(<_i3.PdfFile>[]))
          as _i7.Future<List<_i3.PdfFile>>);
  @override
  _i7.Future<_i3.PdfFile> endTranslationFile(int? id) =>
      (super.noSuchMethod(Invocation.method(#endTranslationFile, [id]),
              returnValue: Future<_i3.PdfFile>.value(_FakePdfFile_1()))
          as _i7.Future<_i3.PdfFile>);
  @override
  _i7.Future<_i4.File> getGeneratedPdf(_i3.PdfFile? file) =>
      (super.noSuchMethod(Invocation.method(#getGeneratedPdf, [file]),
              returnValue: Future<_i4.File>.value(_FakeFile_2()))
          as _i7.Future<_i4.File>);
}

/// A class which mocks [PhotosTranslatorLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhotosTranslatorLocalDataSource extends _i1.Mock
    implements _i8.PhotosTranslatorLocalDataSource {
  MockPhotosTranslatorLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get translating =>
      (super.noSuchMethod(Invocation.getter(#translating), returnValue: false)
          as bool);
  @override
  _i7.Future<void> createTranslationsFile(_i2.TranslationsFile? newFile) =>
      (super.noSuchMethod(Invocation.method(#createTranslationsFile, [newFile]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<void> saveUncompletedTranslation(String? photoUrl) => (super
      .noSuchMethod(Invocation.method(#saveUncompletedTranslation, [photoUrl]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<_i5.Translation> translate(
          _i5.Translation? uncompletedTranslation, int? translationsFileId) =>
      (super.noSuchMethod(
              Invocation.method(
                  #translate, [uncompletedTranslation, translationsFileId]),
              returnValue: Future<_i5.Translation>.value(_FakeTranslation_3()))
          as _i7.Future<_i5.Translation>);
  @override
  _i7.Future<void> updateTranslation(
          int? fileId, _i5.Translation? translation) =>
      (super.noSuchMethod(
          Invocation.method(#updateTranslation, [fileId, translation]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<void> endTranslationsFileCreation() =>
      (super.noSuchMethod(Invocation.method(#endTranslationsFileCreation, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<List<_i2.TranslationsFile>> getTranslationsFiles() =>
      (super.noSuchMethod(Invocation.method(#getTranslationsFiles, []),
              returnValue: Future<List<_i2.TranslationsFile>>.value(
                  <_i2.TranslationsFile>[]))
          as _i7.Future<List<_i2.TranslationsFile>>);
  @override
  _i7.Future<_i2.TranslationsFile> getTranslationsFile(int? fileId) =>
      (super.noSuchMethod(Invocation.method(#getTranslationsFile, [fileId]),
              returnValue:
                  Future<_i2.TranslationsFile>.value(_FakeTranslationsFile_0()))
          as _i7.Future<_i2.TranslationsFile>);
  @override
  _i7.Future<List<_i3.PdfFile>> getPdfFiles() =>
      (super.noSuchMethod(Invocation.method(#getPdfFiles, []),
              returnValue: Future<List<_i3.PdfFile>>.value(<_i3.PdfFile>[]))
          as _i7.Future<List<_i3.PdfFile>>);
  @override
  _i7.Future<void> updatePdfFiles(List<_i3.PdfFile>? files) =>
      (super.noSuchMethod(Invocation.method(#updatePdfFiles, [files]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<void> addPdfFile(_i3.PdfFile? file) =>
      (super.noSuchMethod(Invocation.method(#addPdfFile, [file]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<_i2.TranslationsFile?> getCurrentCreatedFile() =>
      (super.noSuchMethod(Invocation.method(#getCurrentCreatedFile, []),
              returnValue: Future<_i2.TranslationsFile?>.value())
          as _i7.Future<_i2.TranslationsFile?>);
  @override
  _i7.Future<void> removeTranslationsFile(_i2.TranslationsFile? file) =>
      (super.noSuchMethod(Invocation.method(#removeTranslationsFile, [file]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
}

/// A class which mocks [File].
///
/// See the documentation for Mockito's code generation for more information.
class MockFile extends _i1.Mock implements _i4.File {
  MockFile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.File get absolute => (super.noSuchMethod(Invocation.getter(#absolute),
      returnValue: _FakeFile_2()) as _i4.File);
  @override
  String get path =>
      (super.noSuchMethod(Invocation.getter(#path), returnValue: '') as String);
  @override
  Uri get uri =>
      (super.noSuchMethod(Invocation.getter(#uri), returnValue: _FakeUri_4())
          as Uri);
  @override
  bool get isAbsolute =>
      (super.noSuchMethod(Invocation.getter(#isAbsolute), returnValue: false)
          as bool);
  @override
  _i4.Directory get parent => (super.noSuchMethod(Invocation.getter(#parent),
      returnValue: _FakeDirectory_5()) as _i4.Directory);
  @override
  _i7.Future<_i4.File> create({bool? recursive = false}) => (super.noSuchMethod(
          Invocation.method(#create, [], {#recursive: recursive}),
          returnValue: Future<_i4.File>.value(_FakeFile_2()))
      as _i7.Future<_i4.File>);
  @override
  void createSync({bool? recursive = false}) => super.noSuchMethod(
      Invocation.method(#createSync, [], {#recursive: recursive}),
      returnValueForMissingStub: null);
  @override
  _i7.Future<_i4.File> rename(String? newPath) =>
      (super.noSuchMethod(Invocation.method(#rename, [newPath]),
              returnValue: Future<_i4.File>.value(_FakeFile_2()))
          as _i7.Future<_i4.File>);
  @override
  _i4.File renameSync(String? newPath) =>
      (super.noSuchMethod(Invocation.method(#renameSync, [newPath]),
          returnValue: _FakeFile_2()) as _i4.File);
  @override
  _i7.Future<_i4.File> copy(String? newPath) =>
      (super.noSuchMethod(Invocation.method(#copy, [newPath]),
              returnValue: Future<_i4.File>.value(_FakeFile_2()))
          as _i7.Future<_i4.File>);
  @override
  _i4.File copySync(String? newPath) =>
      (super.noSuchMethod(Invocation.method(#copySync, [newPath]),
          returnValue: _FakeFile_2()) as _i4.File);
  @override
  _i7.Future<int> length() =>
      (super.noSuchMethod(Invocation.method(#length, []),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  int lengthSync() =>
      (super.noSuchMethod(Invocation.method(#lengthSync, []), returnValue: 0)
          as int);
  @override
  _i7.Future<DateTime> lastAccessed() =>
      (super.noSuchMethod(Invocation.method(#lastAccessed, []),
              returnValue: Future<DateTime>.value(_FakeDateTime_6()))
          as _i7.Future<DateTime>);
  @override
  DateTime lastAccessedSync() =>
      (super.noSuchMethod(Invocation.method(#lastAccessedSync, []),
          returnValue: _FakeDateTime_6()) as DateTime);
  @override
  _i7.Future<dynamic> setLastAccessed(DateTime? time) =>
      (super.noSuchMethod(Invocation.method(#setLastAccessed, [time]),
          returnValue: Future<dynamic>.value()) as _i7.Future<dynamic>);
  @override
  void setLastAccessedSync(DateTime? time) =>
      super.noSuchMethod(Invocation.method(#setLastAccessedSync, [time]),
          returnValueForMissingStub: null);
  @override
  _i7.Future<DateTime> lastModified() =>
      (super.noSuchMethod(Invocation.method(#lastModified, []),
              returnValue: Future<DateTime>.value(_FakeDateTime_6()))
          as _i7.Future<DateTime>);
  @override
  DateTime lastModifiedSync() =>
      (super.noSuchMethod(Invocation.method(#lastModifiedSync, []),
          returnValue: _FakeDateTime_6()) as DateTime);
  @override
  _i7.Future<dynamic> setLastModified(DateTime? time) =>
      (super.noSuchMethod(Invocation.method(#setLastModified, [time]),
          returnValue: Future<dynamic>.value()) as _i7.Future<dynamic>);
  @override
  void setLastModifiedSync(DateTime? time) =>
      super.noSuchMethod(Invocation.method(#setLastModifiedSync, [time]),
          returnValueForMissingStub: null);
  @override
  _i7.Future<_i4.RandomAccessFile> open(
          {_i4.FileMode? mode = _i4.FileMode.read}) =>
      (super.noSuchMethod(Invocation.method(#open, [], {#mode: mode}),
              returnValue:
                  Future<_i4.RandomAccessFile>.value(_FakeRandomAccessFile_7()))
          as _i7.Future<_i4.RandomAccessFile>);
  @override
  _i4.RandomAccessFile openSync({_i4.FileMode? mode = _i4.FileMode.read}) =>
      (super.noSuchMethod(Invocation.method(#openSync, [], {#mode: mode}),
          returnValue: _FakeRandomAccessFile_7()) as _i4.RandomAccessFile);
  @override
  _i7.Stream<List<int>> openRead([int? start, int? end]) =>
      (super.noSuchMethod(Invocation.method(#openRead, [start, end]),
          returnValue: Stream<List<int>>.empty()) as _i7.Stream<List<int>>);
  @override
  _i4.IOSink openWrite(
          {_i4.FileMode? mode = _i4.FileMode.write,
          _i9.Encoding? encoding = const _i9.Utf8Codec()}) =>
      (super.noSuchMethod(
          Invocation.method(#openWrite, [], {#mode: mode, #encoding: encoding}),
          returnValue: _FakeIOSink_8()) as _i4.IOSink);
  @override
  _i7.Future<_i10.Uint8List> readAsBytes() =>
      (super.noSuchMethod(Invocation.method(#readAsBytes, []),
              returnValue: Future<_i10.Uint8List>.value(_i10.Uint8List(0)))
          as _i7.Future<_i10.Uint8List>);
  @override
  _i10.Uint8List readAsBytesSync() =>
      (super.noSuchMethod(Invocation.method(#readAsBytesSync, []),
          returnValue: _i10.Uint8List(0)) as _i10.Uint8List);
  @override
  _i7.Future<String> readAsString(
          {_i9.Encoding? encoding = const _i9.Utf8Codec()}) =>
      (super.noSuchMethod(
          Invocation.method(#readAsString, [], {#encoding: encoding}),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  String readAsStringSync({_i9.Encoding? encoding = const _i9.Utf8Codec()}) =>
      (super.noSuchMethod(
          Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
          returnValue: '') as String);
  @override
  _i7.Future<List<String>> readAsLines(
          {_i9.Encoding? encoding = const _i9.Utf8Codec()}) =>
      (super.noSuchMethod(
              Invocation.method(#readAsLines, [], {#encoding: encoding}),
              returnValue: Future<List<String>>.value(<String>[]))
          as _i7.Future<List<String>>);
  @override
  List<String> readAsLinesSync(
          {_i9.Encoding? encoding = const _i9.Utf8Codec()}) =>
      (super.noSuchMethod(
          Invocation.method(#readAsLinesSync, [], {#encoding: encoding}),
          returnValue: <String>[]) as List<String>);
  @override
  _i7.Future<_i4.File> writeAsBytes(List<int>? bytes,
          {_i4.FileMode? mode = _i4.FileMode.write, bool? flush = false}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #writeAsBytes, [bytes], {#mode: mode, #flush: flush}),
              returnValue: Future<_i4.File>.value(_FakeFile_2()))
          as _i7.Future<_i4.File>);
  @override
  void writeAsBytesSync(List<int>? bytes,
          {_i4.FileMode? mode = _i4.FileMode.write, bool? flush = false}) =>
      super.noSuchMethod(
          Invocation.method(
              #writeAsBytesSync, [bytes], {#mode: mode, #flush: flush}),
          returnValueForMissingStub: null);
  @override
  _i7.Future<_i4.File> writeAsString(String? contents,
          {_i4.FileMode? mode = _i4.FileMode.write,
          _i9.Encoding? encoding = const _i9.Utf8Codec(),
          bool? flush = false}) =>
      (super.noSuchMethod(
              Invocation.method(#writeAsString, [contents],
                  {#mode: mode, #encoding: encoding, #flush: flush}),
              returnValue: Future<_i4.File>.value(_FakeFile_2()))
          as _i7.Future<_i4.File>);
  @override
  void writeAsStringSync(String? contents,
          {_i4.FileMode? mode = _i4.FileMode.write,
          _i9.Encoding? encoding = const _i9.Utf8Codec(),
          bool? flush = false}) =>
      super.noSuchMethod(
          Invocation.method(#writeAsStringSync, [contents],
              {#mode: mode, #encoding: encoding, #flush: flush}),
          returnValueForMissingStub: null);
  @override
  _i7.Future<bool> exists() =>
      (super.noSuchMethod(Invocation.method(#exists, []),
          returnValue: Future<bool>.value(false)) as _i7.Future<bool>);
  @override
  bool existsSync() => (super.noSuchMethod(Invocation.method(#existsSync, []),
      returnValue: false) as bool);
  @override
  _i7.Future<String> resolveSymbolicLinks() =>
      (super.noSuchMethod(Invocation.method(#resolveSymbolicLinks, []),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  String resolveSymbolicLinksSync() =>
      (super.noSuchMethod(Invocation.method(#resolveSymbolicLinksSync, []),
          returnValue: '') as String);
  @override
  _i7.Future<_i4.FileStat> stat() =>
      (super.noSuchMethod(Invocation.method(#stat, []),
              returnValue: Future<_i4.FileStat>.value(_FakeFileStat_9()))
          as _i7.Future<_i4.FileStat>);
  @override
  _i4.FileStat statSync() =>
      (super.noSuchMethod(Invocation.method(#statSync, []),
          returnValue: _FakeFileStat_9()) as _i4.FileStat);
  @override
  _i7.Future<_i4.FileSystemEntity> delete({bool? recursive = false}) => (super
      .noSuchMethod(Invocation.method(#delete, [], {#recursive: recursive}),
          returnValue: Future<_i4.FileSystemEntity>.value(
              _FakeFileSystemEntity_10())) as _i7.Future<_i4.FileSystemEntity>);
  @override
  void deleteSync({bool? recursive = false}) => super.noSuchMethod(
      Invocation.method(#deleteSync, [], {#recursive: recursive}),
      returnValueForMissingStub: null);
  @override
  _i7.Stream<_i4.FileSystemEvent> watch(
          {int? events = 15, bool? recursive = false}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #watch, [], {#events: events, #recursive: recursive}),
              returnValue: Stream<_i4.FileSystemEvent>.empty())
          as _i7.Stream<_i4.FileSystemEvent>);
}
