// Mocks generated by Mockito 5.3.0 from annotations
// in vido/test/features/files_navigator/data/repository/files_navigator_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i12;
import 'dart:io' as _i3;
import 'dart:typed_data' as _i13;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vido/core/domain/file_parent_type.dart' as _i6;
import 'package:vido/core/external/user_extra_info_getter.dart' as _i10;
import 'package:vido/features/files_navigator/data/app_files_receiver.dart'
    as _i11;
import 'package:vido/features/files_navigator/data/data_sources/files_navigator_local_data_source.dart'
    as _i9;
import 'package:vido/features/files_navigator/data/data_sources/files_navigator_remote_data_source.dart'
    as _i4;
import 'package:vido/features/files_navigator/domain/entities/search_appearance.dart'
    as _i8;
import 'package:vido/features/photos_translator/domain/entities/app_file.dart'
    as _i2;
import 'package:vido/features/photos_translator/domain/entities/pdf_file.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppFile_0 extends _i1.SmartFake implements _i2.AppFile {
  _FakeAppFile_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeFile_1 extends _i1.SmartFake implements _i3.File {
  _FakeFile_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeUri_2 extends _i1.SmartFake implements Uri {
  _FakeUri_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeDirectory_3 extends _i1.SmartFake implements _i3.Directory {
  _FakeDirectory_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeDateTime_4 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeRandomAccessFile_5 extends _i1.SmartFake
    implements _i3.RandomAccessFile {
  _FakeRandomAccessFile_5(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeIOSink_6 extends _i1.SmartFake implements _i3.IOSink {
  _FakeIOSink_6(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeFileStat_7 extends _i1.SmartFake implements _i3.FileStat {
  _FakeFileStat_7(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeFileSystemEntity_8 extends _i1.SmartFake
    implements _i3.FileSystemEntity {
  _FakeFileSystemEntity_8(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [FilesNavigatorRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilesNavigatorRemoteDataSource extends _i1.Mock
    implements _i4.FilesNavigatorRemoteDataSource {
  MockFilesNavigatorRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.AppFile>> getChildren(
          int? folderId, _i6.FileParentType? parentType, String? accessToken) =>
      (super.noSuchMethod(
          Invocation.method(#getChildren, [folderId, parentType, accessToken]),
          returnValue:
              _i5.Future<List<_i2.AppFile>>.value(<_i2.AppFile>[])) as _i5
          .Future<List<_i2.AppFile>>);
  @override
  _i5.Future<_i2.AppFile> getParentWithBrothers(
          int? folderId, String? accessToken) =>
      (super.noSuchMethod(
          Invocation.method(#getParentWithBrothers, [folderId, accessToken]),
          returnValue: _i5.Future<_i2.AppFile>.value(_FakeAppFile_0(
              this,
              Invocation.method(
                  #getParentWithBrothers, [folderId, accessToken])))) as _i5
          .Future<_i2.AppFile>);
  @override
  _i5.Future<_i3.File> getGeneratedPdf(
          _i7.PdfFile? file, String? accessToken) =>
      (super.noSuchMethod(
              Invocation.method(#getGeneratedPdf, [file, accessToken]),
              returnValue: _i5.Future<_i3.File>.value(_FakeFile_1(this,
                  Invocation.method(#getGeneratedPdf, [file, accessToken]))))
          as _i5.Future<_i3.File>);
  @override
  _i5.Future<List<_i8.SearchAppearance>> search(String? text) =>
      (super.noSuchMethod(Invocation.method(#search, [text]),
              returnValue: _i5.Future<List<_i8.SearchAppearance>>.value(
                  <_i8.SearchAppearance>[]))
          as _i5.Future<List<_i8.SearchAppearance>>);
}

/// A class which mocks [FilesNavigatorLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilesNavigatorLocalDataSource extends _i1.Mock
    implements _i9.FilesNavigatorLocalDataSource {
  MockFilesNavigatorLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> setCurrentFileId(int? id) => (super.noSuchMethod(
      Invocation.method(#setCurrentFileId, [id]),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> setFilesTreeLvl(int? lvl) => (super.noSuchMethod(
      Invocation.method(#setFilesTreeLvl, [lvl]),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> setParentId(int? id) => (super.noSuchMethod(
      Invocation.method(#setParentId, [id]),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<int> getCurrentFileId() =>
      (super.noSuchMethod(Invocation.method(#getCurrentFileId, []),
          returnValue: _i5.Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<int?> getFilesTreeLevel() =>
      (super.noSuchMethod(Invocation.method(#getFilesTreeLevel, []),
          returnValue: _i5.Future<int?>.value()) as _i5.Future<int?>);
  @override
  _i5.Future<int> getParentId() =>
      (super.noSuchMethod(Invocation.method(#getParentId, []),
          returnValue: _i5.Future<int>.value(0)) as _i5.Future<int>);
}

/// A class which mocks [UserExtraInfoGetter].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserExtraInfoGetter extends _i1.Mock
    implements _i10.UserExtraInfoGetter {
  MockUserExtraInfoGetter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> getAccessToken() =>
      (super.noSuchMethod(Invocation.method(#getAccessToken, []),
          returnValue: _i5.Future<String>.value('')) as _i5.Future<String>);
  @override
  _i5.Future<int> getId() => (super.noSuchMethod(Invocation.method(#getId, []),
      returnValue: _i5.Future<int>.value(0)) as _i5.Future<int>);
}

/// A class which mocks [AppFilesReceiver].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppFilesReceiver extends _i1.Mock implements _i11.AppFilesReceiver {
  MockAppFilesReceiver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> setAppFiles(List<_i2.AppFile>? files) => (super.noSuchMethod(
      Invocation.method(#setAppFiles, [files]),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
}

/// A class which mocks [File].
///
/// See the documentation for Mockito's code generation for more information.
class MockFile extends _i1.Mock implements _i3.File {
  MockFile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.File get absolute => (super.noSuchMethod(Invocation.getter(#absolute),
          returnValue: _FakeFile_1(this, Invocation.getter(#absolute)))
      as _i3.File);
  @override
  String get path =>
      (super.noSuchMethod(Invocation.getter(#path), returnValue: '') as String);
  @override
  Uri get uri => (super.noSuchMethod(Invocation.getter(#uri),
      returnValue: _FakeUri_2(this, Invocation.getter(#uri))) as Uri);
  @override
  bool get isAbsolute =>
      (super.noSuchMethod(Invocation.getter(#isAbsolute), returnValue: false)
          as bool);
  @override
  _i3.Directory get parent => (super.noSuchMethod(Invocation.getter(#parent),
          returnValue: _FakeDirectory_3(this, Invocation.getter(#parent)))
      as _i3.Directory);
  @override
  _i5.Future<_i3.File> create({bool? recursive = false}) => (super.noSuchMethod(
          Invocation.method(#create, [], {#recursive: recursive}),
          returnValue: _i5.Future<_i3.File>.value(_FakeFile_1(
              this, Invocation.method(#create, [], {#recursive: recursive}))))
      as _i5.Future<_i3.File>);
  @override
  void createSync({bool? recursive = false}) => super.noSuchMethod(
      Invocation.method(#createSync, [], {#recursive: recursive}),
      returnValueForMissingStub: null);
  @override
  _i5.Future<_i3.File> rename(String? newPath) =>
      (super.noSuchMethod(Invocation.method(#rename, [newPath]),
              returnValue: _i5.Future<_i3.File>.value(
                  _FakeFile_1(this, Invocation.method(#rename, [newPath]))))
          as _i5.Future<_i3.File>);
  @override
  _i3.File renameSync(String? newPath) =>
      (super.noSuchMethod(Invocation.method(#renameSync, [newPath]),
              returnValue:
                  _FakeFile_1(this, Invocation.method(#renameSync, [newPath])))
          as _i3.File);
  @override
  _i5.Future<_i3.File> copy(String? newPath) =>
      (super.noSuchMethod(Invocation.method(#copy, [newPath]),
              returnValue: _i5.Future<_i3.File>.value(
                  _FakeFile_1(this, Invocation.method(#copy, [newPath]))))
          as _i5.Future<_i3.File>);
  @override
  _i3.File copySync(String? newPath) =>
      (super.noSuchMethod(Invocation.method(#copySync, [newPath]),
              returnValue:
                  _FakeFile_1(this, Invocation.method(#copySync, [newPath])))
          as _i3.File);
  @override
  _i5.Future<int> length() =>
      (super.noSuchMethod(Invocation.method(#length, []),
          returnValue: _i5.Future<int>.value(0)) as _i5.Future<int>);
  @override
  int lengthSync() =>
      (super.noSuchMethod(Invocation.method(#lengthSync, []), returnValue: 0)
          as int);
  @override
  _i5.Future<DateTime> lastAccessed() =>
      (super.noSuchMethod(Invocation.method(#lastAccessed, []),
              returnValue: _i5.Future<DateTime>.value(
                  _FakeDateTime_4(this, Invocation.method(#lastAccessed, []))))
          as _i5.Future<DateTime>);
  @override
  DateTime lastAccessedSync() => (super.noSuchMethod(
          Invocation.method(#lastAccessedSync, []),
          returnValue:
              _FakeDateTime_4(this, Invocation.method(#lastAccessedSync, [])))
      as DateTime);
  @override
  _i5.Future<dynamic> setLastAccessed(DateTime? time) =>
      (super.noSuchMethod(Invocation.method(#setLastAccessed, [time]),
          returnValue: _i5.Future<dynamic>.value()) as _i5.Future<dynamic>);
  @override
  void setLastAccessedSync(DateTime? time) =>
      super.noSuchMethod(Invocation.method(#setLastAccessedSync, [time]),
          returnValueForMissingStub: null);
  @override
  _i5.Future<DateTime> lastModified() =>
      (super.noSuchMethod(Invocation.method(#lastModified, []),
              returnValue: _i5.Future<DateTime>.value(
                  _FakeDateTime_4(this, Invocation.method(#lastModified, []))))
          as _i5.Future<DateTime>);
  @override
  DateTime lastModifiedSync() => (super.noSuchMethod(
          Invocation.method(#lastModifiedSync, []),
          returnValue:
              _FakeDateTime_4(this, Invocation.method(#lastModifiedSync, [])))
      as DateTime);
  @override
  _i5.Future<dynamic> setLastModified(DateTime? time) =>
      (super.noSuchMethod(Invocation.method(#setLastModified, [time]),
          returnValue: _i5.Future<dynamic>.value()) as _i5.Future<dynamic>);
  @override
  void setLastModifiedSync(DateTime? time) =>
      super.noSuchMethod(Invocation.method(#setLastModifiedSync, [time]),
          returnValueForMissingStub: null);
  @override
  _i5.Future<_i3.RandomAccessFile> open(
          {_i3.FileMode? mode = _i3.FileMode.read}) =>
      (super.noSuchMethod(Invocation.method(#open, [], {#mode: mode}),
              returnValue: _i5.Future<_i3.RandomAccessFile>.value(
                  _FakeRandomAccessFile_5(
                      this, Invocation.method(#open, [], {#mode: mode}))))
          as _i5.Future<_i3.RandomAccessFile>);
  @override
  _i3.RandomAccessFile openSync({_i3.FileMode? mode = _i3.FileMode.read}) =>
      (super.noSuchMethod(Invocation.method(#openSync, [], {#mode: mode}),
              returnValue: _FakeRandomAccessFile_5(
                  this, Invocation.method(#openSync, [], {#mode: mode})))
          as _i3.RandomAccessFile);
  @override
  _i5.Stream<List<int>> openRead([int? start, int? end]) =>
      (super.noSuchMethod(Invocation.method(#openRead, [start, end]),
          returnValue: _i5.Stream<List<int>>.empty()) as _i5.Stream<List<int>>);
  @override
  _i3.IOSink openWrite(
          {_i3.FileMode? mode = _i3.FileMode.write,
          _i12.Encoding? encoding = const _i12.Utf8Codec()}) =>
      (super.noSuchMethod(
          Invocation.method(#openWrite, [], {#mode: mode, #encoding: encoding}),
          returnValue: _FakeIOSink_6(
              this,
              Invocation.method(
                  #openWrite, [], {#mode: mode, #encoding: encoding}))) as _i3
          .IOSink);
  @override
  _i5.Future<_i13.Uint8List> readAsBytes() =>
      (super.noSuchMethod(Invocation.method(#readAsBytes, []),
              returnValue: _i5.Future<_i13.Uint8List>.value(_i13.Uint8List(0)))
          as _i5.Future<_i13.Uint8List>);
  @override
  _i13.Uint8List readAsBytesSync() =>
      (super.noSuchMethod(Invocation.method(#readAsBytesSync, []),
          returnValue: _i13.Uint8List(0)) as _i13.Uint8List);
  @override
  _i5.Future<String> readAsString(
          {_i12.Encoding? encoding = const _i12.Utf8Codec()}) =>
      (super.noSuchMethod(
          Invocation.method(#readAsString, [], {#encoding: encoding}),
          returnValue: _i5.Future<String>.value('')) as _i5.Future<String>);
  @override
  String readAsStringSync({_i12.Encoding? encoding = const _i12.Utf8Codec()}) =>
      (super.noSuchMethod(
          Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
          returnValue: '') as String);
  @override
  _i5.Future<List<String>> readAsLines(
          {_i12.Encoding? encoding = const _i12.Utf8Codec()}) =>
      (super.noSuchMethod(
              Invocation.method(#readAsLines, [], {#encoding: encoding}),
              returnValue: _i5.Future<List<String>>.value(<String>[]))
          as _i5.Future<List<String>>);
  @override
  List<String> readAsLinesSync(
          {_i12.Encoding? encoding = const _i12.Utf8Codec()}) =>
      (super.noSuchMethod(
          Invocation.method(#readAsLinesSync, [], {#encoding: encoding}),
          returnValue: <String>[]) as List<String>);
  @override
  _i5.Future<_i3.File> writeAsBytes(List<int>? bytes,
          {_i3.FileMode? mode = _i3.FileMode.write, bool? flush = false}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #writeAsBytes, [bytes], {#mode: mode, #flush: flush}),
              returnValue: _i5.Future<_i3.File>.value(_FakeFile_1(this,
                  Invocation.method(#writeAsBytes, [bytes], {#mode: mode, #flush: flush}))))
          as _i5.Future<_i3.File>);
  @override
  void writeAsBytesSync(List<int>? bytes,
          {_i3.FileMode? mode = _i3.FileMode.write, bool? flush = false}) =>
      super.noSuchMethod(
          Invocation.method(
              #writeAsBytesSync, [bytes], {#mode: mode, #flush: flush}),
          returnValueForMissingStub: null);
  @override
  _i5.Future<_i3.File> writeAsString(String? contents,
          {_i3.FileMode? mode = _i3.FileMode.write,
          _i12.Encoding? encoding = const _i12.Utf8Codec(),
          bool? flush = false}) =>
      (super
          .noSuchMethod(Invocation.method(#writeAsString, [contents], {#mode: mode, #encoding: encoding, #flush: flush}),
              returnValue: _i5.Future<_i3.File>.value(_FakeFile_1(
                  this,
                  Invocation.method(#writeAsString, [
                    contents
                  ], {
                    #mode: mode,
                    #encoding: encoding,
                    #flush: flush
                  })))) as _i5.Future<_i3.File>);
  @override
  void writeAsStringSync(String? contents,
          {_i3.FileMode? mode = _i3.FileMode.write,
          _i12.Encoding? encoding = const _i12.Utf8Codec(),
          bool? flush = false}) =>
      super.noSuchMethod(
          Invocation.method(#writeAsStringSync, [contents],
              {#mode: mode, #encoding: encoding, #flush: flush}),
          returnValueForMissingStub: null);
  @override
  _i5.Future<bool> exists() =>
      (super.noSuchMethod(Invocation.method(#exists, []),
          returnValue: _i5.Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  bool existsSync() => (super.noSuchMethod(Invocation.method(#existsSync, []),
      returnValue: false) as bool);
  @override
  _i5.Future<String> resolveSymbolicLinks() =>
      (super.noSuchMethod(Invocation.method(#resolveSymbolicLinks, []),
          returnValue: _i5.Future<String>.value('')) as _i5.Future<String>);
  @override
  String resolveSymbolicLinksSync() =>
      (super.noSuchMethod(Invocation.method(#resolveSymbolicLinksSync, []),
          returnValue: '') as String);
  @override
  _i5.Future<_i3.FileStat> stat() =>
      (super.noSuchMethod(Invocation.method(#stat, []),
              returnValue: _i5.Future<_i3.FileStat>.value(
                  _FakeFileStat_7(this, Invocation.method(#stat, []))))
          as _i5.Future<_i3.FileStat>);
  @override
  _i3.FileStat statSync() => (super.noSuchMethod(
          Invocation.method(#statSync, []),
          returnValue: _FakeFileStat_7(this, Invocation.method(#statSync, [])))
      as _i3.FileStat);
  @override
  _i5.Future<_i3.FileSystemEntity> delete({bool? recursive = false}) => (super
          .noSuchMethod(Invocation.method(#delete, [], {#recursive: recursive}),
              returnValue: _i5.Future<_i3.FileSystemEntity>.value(
                  _FakeFileSystemEntity_8(this,
                      Invocation.method(#delete, [], {#recursive: recursive}))))
      as _i5.Future<_i3.FileSystemEntity>);
  @override
  void deleteSync({bool? recursive = false}) => super.noSuchMethod(
      Invocation.method(#deleteSync, [], {#recursive: recursive}),
      returnValueForMissingStub: null);
  @override
  _i5.Stream<_i3.FileSystemEvent> watch(
          {int? events = 15, bool? recursive = false}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #watch, [], {#events: events, #recursive: recursive}),
              returnValue: _i5.Stream<_i3.FileSystemEvent>.empty())
          as _i5.Stream<_i3.FileSystemEvent>);
}
